//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibles.DataResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bibles.DataResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01O||1||1||In die begin het God die hemel en die aarde geskape.
        ///01O||1||2||En die aarde was woes en leeg, en duisternis was op die wêreldvloed, en die Gees van God het gesweef op die waters.
        ///01O||1||3||En God het gesê: Laat daar lig wees! En daar was lig.
        ///01O||1||4||Toe sien God dat die lig goed was. En God het skeiding gemaak tussen die lig en die duisternis;
        ///01O||1||5||en God het die lig dag genoem, en die duisternis het Hy nag genoem. En dit was aand en dit was môre, die eerste dag.
        ///01O||1||6||En Go [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Afrikaans_1933_56_Hersien {
            get {
                return ResourceManager.GetString("Afrikaans_1933_56_Hersien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01O||1||1||In the beginning God created the heaven and the earth.
        ///01O||1||2||And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.
        ///01O||1||3||And God said, Let there be light: and there was light.
        ///01O||1||4||And God saw the light, that it was good: and God divided the light from the darkness.
        ///01O||1||5||And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_King_James_Version {
            get {
                return ResourceManager.GetString("English_King_James_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01O||1||1||Am Anfang schuf Gott Himmel und Erde.
        ///01O||1||2||Und die Erde war wüst und leer, und es war finster auf der Tiefe; und der Geist Gottes schwebete auf dem Wasser.
        ///01O||1||3||Und Gott sprach: Es werde Licht! Und es ward Licht.
        ///01O||1||4||Und Gott sah, daß das Licht gut war. Da schied Gott das Licht von der Finsternis
        ///01O||1||5||und nannte das Licht Tag und die Finsternis Nacht. Da ward aus Abend und Morgen der erste Tag.
        ///01O||1||6||Und Gott sprach: Es werde eine Feste zwischen den Wassern, und [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string German_Luther_1545 {
            get {
                return ResourceManager.GetString("German_Luther_1545", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01O||1||1||Ekuqalekeni uThixo wadala amazulu nehlabathi.
        ///01O||1||2||Ke ehlabathini kwakusenyanyeni, kuselubala; kwakumnyama phezu kwamanzi enzonzobila. UMoya kaThixo wafukama phezu kwamanzi lawo.
        ///01O||1||3||Wathi uThixo, Makubekho ukukhanya. Kwabakho ke ukukhanya.
        ///01O||1||4||Wakubona ke uThixo ukukhanya ukuba kulungile, wahlula uThixo phakathi kokukhanya nobumnyama.
        ///01O||1||5||Wathi uThixo ukukhanya yimini, wathi ubumnyama bubusuku.  Kwahlwa, kwasa: yangumhla wokuqala.
        ///01O||1||6||Wathi uThixo, Makubekh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xhosa {
            get {
                return ResourceManager.GetString("Xhosa", resourceCulture);
            }
        }
    }
}
