//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibles.DataResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bibles.DataResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01O||1||1||In the beginning God created the heaven and the earth.
        ///01O||1||2||And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.
        ///01O||1||3||And God said, Let there be light: and there was light.
        ///01O||1||4||And God saw the light, that it was good: and God divided the light from the darkness.
        ///01O||1||5||And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English_King_James_Version {
            get {
                return ResourceManager.GetString("English_King_James_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01O||1||1||Ekuqalekeni uThixo wadala amazulu nehlabathi.
        ///01O||1||2||Ke ehlabathini kwakusenyanyeni, kuselubala; kwakumnyama phezu kwamanzi enzonzobila. UMoya kaThixo wafukama phezu kwamanzi lawo.
        ///01O||1||3||Wathi uThixo, Makubekho ukukhanya. Kwabakho ke ukukhanya.
        ///01O||1||4||Wakubona ke uThixo ukukhanya ukuba kulungile, wahlula uThixo phakathi kokukhanya nobumnyama.
        ///01O||1||5||Wathi uThixo ukukhanya yimini, wathi ubumnyama bubusuku.  Kwahlwa, kwasa: yangumhla wokuqala.
        ///01O||1||6||Wathi uThixo, Makubekh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xhosa {
            get {
                return ResourceManager.GetString("Xhosa", resourceCulture);
            }
        }
    }
}
